name: 'buy-me-a-coffee-to-file'
author: 'Akos Balasko'
description: 'This action grabs the latest x messages written by your supporters on Buy Me A Coffee, and  stores them as a designed html file.'

inputs:

  BUY_ME_A_COFFEE_TOKEN:  # id of input
    description: 'Your Buy me a coffee token'
    required: true

  NUMBER_OF_MESSAGES: 
    description: 'Number of the messages to show'
    default: 3

  FILENAME:
    description: "Case sensitive name of your file in where the messages should be stored"
    required: true
runs:
  using: 'node16'
  main: './dist/index.js'
